name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '13,43 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest emotes.json
      run: |-
        curl "https://cdn.destiny.gg/emotes/emotes.json?_=$(date +%s)" | jq > emotes.json
    - name: Fetch latest emotes.css
      run: |-
        curl --output emotes.css "https://cdn.destiny.gg/emotes/emotes.css?_=$(date +%s)"
    - name: Check if anything changed
      id: change_check
      run: |-
        git status --porcelain=v1 2>/dev/null
        echo "GIT_STATUS=$(git status --porcelain=v1 2>/dev/null | wc -l)" >> $GITHUB_OUTPUT
    - name: Remove the specific theme folders
      if: steps.change_check.outputs.GIT_STATUS != '0'
      run: jq -r '"images/theme_" + (.[].theme | tostring)' emotes.json | (xargs rm -r 2> /dev/null || true)
    - name: Fetch latest emote images
      if: steps.change_check.outputs.GIT_STATUS != '0'
      run: |-
        jq -rj '.[] | .image[].url, " ", "images/theme_" + (.theme | tostring) + "/" + .prefix + "." + (.image[].name | split(".") | .[1]), "\n"' emotes.json | xargs -n2 sh -c 'curl --create-dirs -o $1 $0'
    - name: Commit and push if it changed
      if: steps.change_check.outputs.GIT_STATUS != '0'
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push